---
name: Casey Engstrom
position: "PhD Candidate in Molecular Biology"
address: "Simon Fraser University Dept. Molecular Biology and Biochemistry"
www: caseyengstrom.ca
email: cengstro@sfu.ca
twitter: CaseyEngstrom
github: cengstro
aboutme: 
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
csl: apa7.csl
---

<!-- csl from Zotero Style Repository https://www.zotero.org/styles?q=id%3Aapa-cv -->

```{r setup, include=FALSE}
# options(encoding = "UTF-8")
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

source("../scripts/install.R") # load libraries
```

<!-- Todo: -->
<!-- look up names of presentations -->

<!-- add aboutme in yaml header 
    add url to magazine article -->
<!-- add work history -->

```{r get data, include=FALSE}

# Education
edu <- read_csv(here("data/education.csv"))

# Decided not to use scholar because it lacks DOI
# google_scholar <- scholar::get_publications("aST1ItMAAAAJ") %>%
#   dplyr::mutate(author = author %>% as.character(),
#                 first_author = str_split_n(author, ",", 1),
#                 peer_reviewed = case_when(journal %in% c("US Fish and Wildl. Serv. Rep., AMNWR") ~ FALSE,
#                                           TRUE ~ TRUE)) %>%
#   dplyr::arrange(desc(year)) %>%
#   filter(peer_reviewed == TRUE)

# And orcid is just plain confusiong
# orcid <- rorcid::orcid_works("0000-0002-6553-7883")

# Presentations
presentations <- read_csv(here::here("data/presentations.csv")) %>% 
  arrange(desc(when))

# Mentoring
mentoring <- read_csv(here::here("data/mentoring.csv")) %>% 
  arrange(desc(when))

# TA
taing <- read_csv(here::here("data/taing.csv")) %>% 
  arrange(desc(when))

# Workshop leader
workshops <- read_csv(here::here("data/workshops.csv")) %>% 
  arrange(desc(when))

# Skills
skills <- read_csv(here::here("data/skills.csv")) %>% 
  group_by(category) %>% 
  mutate(skill = paste(skill, collapse = ", ")) %>% 
  ungroup %>% 
  unique

# Service
service <- read_csv(here::here("data/service.csv"))

# Jobs
# jobs <- read_csv(here::here("data/jobs.csv"))
```

# Education 
```{r}
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni,
                 why = details)

```

# Publications

<!-- I made folders for my publications in Zotero, and exported as Better Bibtex. (Check export settings in preferences) -->

```{r}
vitae::bibliography_entries(here::here("data/peer-reviewed.bib")) # formatted bibliography as per csl
```

# Science communication

```{r}
bibliography_entries(here::here("data/sci-com.bib"))
```

<!-- \pagebreak -->

# Presentations

```{r}
presentations %>%
  detailed_entries(what = what,
                   when = when,
                   with = with,
                   where = where,
                   why = why,
                   .protect = TRUE)
```

# Workshops taught

```{r}
workshops %>% detailed_entries(what = what, with = with, when = when)
```

# TAing

```{r}
taing %>%
  detailed_entries(what = what, when = when, with = with)
```

# Mentoring

```{r}
mentoring %>%
  detailed_entries(what = what, with = with, when = when)
```

# Service

```{r}
service %>%
  detailed_entries(with = type, when = when, why = details)
```
